---
- name: Updating the apt package index
  shell: apt update

- name: Installing common packages
  shell: apt install -y systemd vim tree curl

- name: add google dns-nameservers
  shell: echo "dns-nameservers 8.8.8.8 8.8.4.4" >> /etc/network/interfaces 