---
- name: Updating the apt package index
  shell: apt update

- name: Installing common packages
  shell: apt install -y systemd vim tree curl htop

- name: Check if /etc/network/interfaces exist
  shell: ls /etc/network/interfaces 
  ignore_errors: yes
  register: network
  changed_when: "network.rc == 0"

- name: Adding google dns-nameservers
  shell: echo "dns-nameservers 8.8.8.8 8.8.4.4" >> /etc/network/interfaces 
  when: network.changed

- name: Getting current hostname
  shell: hostname
  register: hn
  when: hostname != ""

- name: Setting up new hostname
  shell: hostname {{hostname}}
  ignore_errors: yes
  when: hostname != ""

- name: Setting up /etc/hostname
  replace: 
    path: /etc/hostname
    regexp: '{{hn.stdout}}'
    replace: '{{hostname}}'
    backup: yes
  ignore_errors: yes
  when: hostname != ""

- name: Setting up hostname to /etc/hosts
  replace: 
    path: /etc/hosts
    regexp: '{{hn.stdout}}'
    replace: '{{hostname}}'
    backup: yes
  ignore_errors: yes
  when: hostname != ""
