---
- name: Check if openssh server installed
  shell: dpkg --get-selections | grep -v deinstall | grep openssh-server
  ignore_errors: yes
  register: sshd
  changed_when: sshd.rc > 0

- name: Installing openssh-server
  shell: apt-get install -y openssh-server
  when: sshd.changed

- name: Copying .ssh to root
  shell: cp -r {{ ssh.path }}/* /root/.ssh
