# 設定 hostname, 放空白代表不修改
hostname: ""
ssh:
  path: "/home/ubuntu/.ssh"
  key: "/home/ubuntu/support.pem"
docker: 
  # 是否要安裝 docker?
  enabled: true
  # 要安裝的 docker 版本, 若要安裝最新的則修改成: docker-ce
  version: docker-ce=18.06.2~ce~3-0~ubuntu
  # 要信任哪個非 https 的 docker registry, 
  insecure:
    # 此 enable 的判斷獨立於 docker.enabled 之外
    enabled: true
    registries: 
      - icp-registry:5000
nfs:
  client:
    # 是否要安裝 nfs client package ?
    enabled: true
    mount: 
      device: 192.168.1.60:/nfs
      point: /nfs
  server: 
    # 是否安裝 nfs server package?
    enabled: false
